---

- name: Gestione pacchetti # nome del Play
  hosts: localhost # esegue il playbook sulla macchina locale
  connection: local # esegue i comandi direttamente in locale

  vars: # variabili
    software: # dizionario che contiene i pacchetti e i loro stati
      present: # la lista dei pacchetti che vogliamo installare
        - vim
        - git
        - telnet
        - nano
      absent: # la lista dei pacchetti che vogliamo disinstallare
        - openssh
  
  tasks: # azioni da eseguire
    - name: Installazione dei pacchetti # nome della task
      ansible.builtin.package: # modulo per la gestione dei pacchetti
        name: "{{ item }}" # verranno passati i valori della lista dei pacchetti da installare
        state: present # lo stato che vogliamo ottenere
      loop: "{{ software.present }}" # il ciclo che scorre la lista
      when: software.present is defined # esegue le azioni solo se la lista è definita

    - name: Rimozione dei pacchetti # nome della task 
      ansible.builtin.package: # modulo per la gestione dei pacchetti
        name: "{{ item }}" # verranno passati i valori della lista dei pacchetti da disinstallare
        state: absent # lo stato che vogliamo ottenere
      loop: "{{ software.absent }}" # il ciclo che scorre la lista
      when: software.absent is defined # esegue le azioni solo se la lista è definita

...      