Vagrant.configure("2") do |config|
  
  # immagine base 
  config.vm.box = "bento/ubuntu-24.04"

  # VM 1: SPONDA INIZIALE
  config.vm.define "sponda_iniziale" do |sponda_iniziale|
    sponda_iniziale.vm.hostname = "sponda-iniziale"
    # IP per la rete privata interna
    sponda_iniziale.vm.network "private_network", ip: "192.168.56.10"
    # condivisione della cartella per gli script     
    sponda_iniziale.vm.synced_folder ".", "/app"
  end

  # VM 2: SPONDA FINALE 
  config.vm.define "sponda_finale" do |sponda_finale|
    sponda_finale.vm.hostname = "sponda-finale"
    # IP per la rete privata interna
    sponda_finale.vm.network "private_network", ip: "192.168.56.20"
    # condivisione della cartella per gli script 
    sponda_finale.vm.synced_folder ".", "/app"
  end

  # risorse
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

end