pipeline {
    agent { // container
        docker {
            image 'rockylinux/rockylinux:9'
        }
    }

    stages {
        stage('Selezione dell\' Ambiente') {
            steps {
                script {
                    // menù interattivo
                    env.ENVIRONMENT = input(
                        message: 'Seleziona lo stage da eseguire',
                        ok: 'Continua',
                        parameters: [
                            choice(
                                name: 'ENVIRONMENT', 
                                choices: ['DEVELOPMENT', 'PRODUCTION'], 
                                description: 'Quale ambiente vuoi avviare?'
                            )
                        ]
                    )
                }
            }
        }

        stage('PRODUCTION') {
            when { //controllo 
                environment name: 'ENVIRONMENT', value: 'PRODUCTION'
            }
            
            steps {
                echo "E' stato selezionato ${env.ENVIRONMENT}"
                echo "Ambiente di PRODUCTION"
            }
        }

        stage('DEVELOPMENT') {
            when { //controllo 
                environment name: 'ENVIRONMENT', value: 'DEVELOPMENT'
            }
            
            steps {
                echo "E' stato selezionato ${env.ENVIRONMENT}"
                echo "Ambiente di DEVELOPMENT"
            }
        }
    }
}