 pipeline {
    agent {
        docker {  
            image 'rockylinux/rockylinux:9'
        }
    }

    environment {
        APP_NAME = 'my-web-app'
    } 

    stages{
        stage('Stage 1 : Prep & Test'){
            steps{
                dir('doc'){
                    script{
                        sh 'echo Avvio dei test per ${APP_NAME}...'
                        sh 'echo Running unit tests...'
                    }
                }
            }
        }
        stage('Stage 2 : Build'){
            steps{
                dir('doc'){
                    script{
                        sh 'echo Building artifact...'
                    }
                }
            }
        }
        stage('Stage 3 : Deploy'){
            when {
                branch 'main'
                }
            steps{
                dir('doc'){
                    script{
                        sh 'echo Deploy...'
                    }
                }
            }
        }
    }

    post {
        always {
            sh "echo Pulizia completata."
        }

        success {
            sh "echo Pipeline completata con successo!"
        }

        failure {
            sh "echo Errore nella pipeline."
        }
    }
}