 pipeline {
    agent {
        docker{  
            'rockylinux/rockylinux:9'
        }
    }

    stages {
        stage('stage1') {
            steps {
                dir('Documents') {
                    script {
                        sh 'echo "ciao" > jenkinswashere.txt'
                    }
                }
            }
        }
    }
}