Vagrant.configure("2") do |config|    
  # immagine base 
  config.vm.box = "bento/ubuntu-24.04"

  # configurazione globale
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  # configurazione reverse proxy 
  config.vm.define "proxy-server" do |proxy|
    proxy.vm.hostname = "serverUbuntuServer"
    proxy.vm.network :private_network, ip: "192.168.56.10"
    
    # risoluzione collisione porte
    proxy.vm.network "forwarded_port", guest: 80, host: 8085, id: "http-proxy", auto_correct: true
    proxy.vm.network "forwarded_port", guest: 443, host: 8443, id: "https-proxy", auto_correct: true
  
    # provisioning
    proxy.vm.provision "shell", path: File.expand_path("provision/proxy/setup.sh", __dir__)
  end

  # configurazione server 1
  config.vm.define "server1" do |server1|
    server1.vm.hostname = "srv-1"
    server1.vm.network :private_network, ip: "192.168.56.20"
    
    # provisioning
    server1.vm.provision "shell", path: File.expand_path("provision/backend/setup.sh", __dir__)
  end

  # configurazione server 2
  config.vm.define "server2" do |server2|
    server2.vm.hostname = "srv-2"
    server2.vm.network :private_network, ip: "192.168.56.30"

    # provisioning
    server2.vm.provision "shell", path: File.expand_path("provision/backend/setup.sh", __dir__)
  end
end